# @software: PyCharm
# @author: Lionel Johnson
# @contact: https://fairy.host
# @organization: https://github.com/FairylandFuture
# @since: 05 19, 2024
---
mysql:
  host: localhost
  port: 3306
  user: root
  password: root
  database: mysql
postgresql:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  database: postgres
  schema: public
